# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Armor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('armor_bonus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item_Damage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('damage_bonus', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
