# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp1', '0002_auto_20160822_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('bonus', models.IntegerField()),
                ('modif', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Item_Armor',
        ),
        migrations.DeleteModel(
            name='Item_Damage',
        ),
    ]
