# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp1', '0007_auto_20160824_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='dex',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='player',
            name='dmg',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='player',
            name='hp',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='player',
            name='intel',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='player',
            name='mp',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.IntegerField(choices=[(0, 'dead'), (1, 'alive')], default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='strength',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='player',
            name='weapon',
            field=models.IntegerField(default=5),
        ),
    ]
