# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp1', '0009_fit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fit',
        ),
    ]
