# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp1', '0010_delete_fit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='mp',
            field=models.IntegerField(default=10),
        ),
    ]
